### ISSUE TITLE
itdb1.23 items Can not add and modify Racks 

### ISSUE THREAD

**Issue by dickyieong** [sivann/itdb#53]
V itdb1.23 items Can not add and modify Racks 。
https://github.com/sivann/itdb/archive/1.23.zip

![rack-01](https://cloud.githubusercontent.com/assets/20552736/16979507/fd27165a-4e93-11e6-95ae-7b89154e071b.jpg)
![rack-02](https://cloud.githubusercontent.com/assets/20552736/16979508/fd2c8b58-4e93-11e6-86a4-84364be0f83e.jpg)
![rack-03](https://cloud.githubusercontent.com/assets/20552736/16979509/fd302d8a-4e93-11e6-9dfa-04e9c52eb515.jpg)

THX

DY DICKY EMAIL:6860597@gmail.com

**Comment by sivann** [comment]
confirmed

**Comment by dickyieong** [comment]
confirmed? 
Interface device can not join the Rack
But can add  Rack

**Comment by sivann** [comment]
Yes, I know. The bug has been confirmed. I'm working on a fix.

**Comment by dickyieong** [comment]
Expect to solve the problem, ITDB is a good product

**Comment by sivann** [comment]
Sorry, my bad. I cannot reproduce the error. 

- Make sure that on your rack definitions the location of the rack is the same as the location of the item.
- What happens if you select another "location" on the item definition? Does the rack select box change? 
- Is anything logged on the apahce error.log?
- What is your linux distribution/version, apache release

**Comment by dickyieong** [comment]
THX Sivann  I FIX the error

**Comment by sivann** [comment]
Glad you did.
